name: Say hello

on:
  pull_request:
    branches:
      - main

jobs:
  hello_world:
    runs-on: ubuntu-18.04
    steps:
      - name: Echo the message
        run: |
          echo "Hola people"
      - name: Dime la fecha
        run: date
      - run: ls -l 
 